/*
 * NUMBER_DEFINE.hpp
 *
 *  Created on: 2022年12月2日
 *      Author: fenghe
 */

#ifndef SRC_BWT_ONLINE_NUM_DEF_HPP_
#define SRC_BWT_ONLINE_NUM_DEF_HPP_

//BASIC
#define MANAGER_OCC_BLOCK 0x200 //512
#define NUM_READS_PER_EXEC_BLK 0x40000 //32K right-now；0.25M = 2^18 = 2^(2+ 4*4) = 0x40000 //todo
#define KL_SIZE 10
#define KL_SIZE_BLOCK_SIZE (KL_SIZE * NUM_READS_PER_EXEC_BLK)
#define MANAGER_SEQ_SIZE (MANAGER_OCC_BLOCK * NUM_READS_PER_EXEC_BLK) //512 * 1M
#define MAX_CHIP_RECORD_NUM_PER_TYPE (0x400000 * 0x100000) // 4194304*1M//??

//for OCC
#define NUM_READS_PER_EXEC_BLK_OCC NUM_READS_PER_EXEC_BLK //1M
#define MANAGER_SEQ_SIZE_OCC MANAGER_SEQ_SIZE //512 * 1M
#define ALN_STEP_NUM 5
#define ALN_PIPELINE_T_NUM 1//ALN_STEP_NUM

//for SA
#define NUM_READS_PER_EXEC_BLK_SA NUM_READS_PER_EXEC_BLK //1M
#define MANAGER_SEQ_SIZE_SA MANAGER_SEQ_SIZE //512 * 1M
#define MANAGER_SA_BLOCK MANAGER_OCC_BLOCK //512

#define SA_PAIRING_STEP_NUM 3
#define SA_PAIRING_PIPELINE_T_NUM SA_PAIRING_STEP_NUM
#define SKIP_SA_K_VALUE 0xffffffff
#define SKIP_SA_L_VALUE 0x00000000

//for BARCODE:
#define BARCODE_LOAD_PER_TIME NUM_READS_PER_EXEC_BLK //1M
#define BARCODE_MAX MANAGER_SEQ_SIZE //1M
//for SAMPLE
#define MAX_SAMPLE_ID 0x10000 //at most 64K samples

//for gap alignment
#define GAP_ALN_STORE__SMALL_MAX__ 10
#define GAP_ALN_STORE_TYPE_NULL 0
#define GAP_ALN_STORE_TYPE_UNIQ 1
#define GAP_ALN_STORE_TYPE_SMALL 2
#define GAP_ALN_STORE_TYPE_BIG 3

#endif /* SRC_BWT_ONLINE_NUM_DEF_HPP_ */
